syntax = "proto3";

option csharp_namespace = "GrpcCommonNet.Library.User";

import "google/protobuf/field_mask.proto";
import "protos/common/general.proto";
import "protos/common/user.proto";

package User;

service UserServices {
	rpc GetUser(UserRequest) returns (UserResponse);
	rpc GetListUser(UserFilterRequest) returns (ListUserResponse);
	rpc CreateUser(CreateUserRequest) returns (UserResponse);
	rpc UpdateUser(UpdateUserRequest) returns (UserResponse);
	rpc DeleteUser(DeleteUserRequest) returns (DeleteUserResponse);
	rpc DeleteIdsUser(DeleteIdsUserRequest) returns (UndeleteIdsUserResponse);
}

message UserRequest {
	int32 user_id = 1;
}

message UserResponse {
	Common.Result result = 1;
	Common.User user = 2;
}

message UserFilterRequest {
	optional string user_login = 1;
	optional int32 contragent_id = 2;
	optional bool user_is_blocked = 3;
	optional bool user_access = 4;
	optional string application_name = 5;
	google.protobuf.FieldMask field_mask = 6;	
}

message ListUserResponse {
	Common.Result result = 1;
	repeated Common.User users = 2;
}	

message CreateUserRequest {
	int32 contragent_id = 1;
	string user_login = 2;
	string user_password = 3;
	string user_symbol = 4;
	optional bool user_is_blocked = 5;
	optional bool user_access = 6;
}

message UpdateUserRequest {
	int32 user_id = 1;
	optional int32 contragent_id = 2;
	optional string user_login = 3;
	optional string user_password = 4;
	optional string user_symbol = 5;
	optional bool user_is_blocked = 6;
	optional bool user_access = 7;
}

message DeleteUserRequest {
	int32 user_id = 1;
}

message DeleteUserResponse {
	Common.Result result = 1;
}

message DeleteIdsUserRequest {
	repeated int32 ids = 1;
}

message UndeleteIdsUserResponse {
	Common.Result result = 1;
	repeated int32 undeleted_ids = 2;
}



