
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Objects\Contracts\Forms\ContractsForm.resx~RF3ff13d93.TMP" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="C1.Excel" Version="9.0.20251.144" />
    <PackageReference Include="C1.Win.Calendar" Version="8.0.20251.708" />
    <PackageReference Include="C1.Win.FlexGrid" Version="8.0.20251.708" />
    <PackageReference Include="C1.Win.Input" Version="8.0.20251.708" />
    <PackageReference Include="C1.Win.Input.MultiColumnCombo" Version="8.0.20251.708" />
    <PackageReference Include="C1.Win.SplitContainer" Version="8.0.20251.708" />
    <PackageReference Include="Grpc.Net.Client" Version="2.76.0" />
    <PackageReference Include="Google.Protobuf" Version="3.33.2" />
    <PackageReference Include="Grpc.Core.Api" Version="2.76.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="SmartGrid" Version="8.0.0.3" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Objects\Geolocations\Places\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GrpcCommonNet.Proto\GrpcCommonNet.Proto.csproj" />
  </ItemGroup>
</Project>
