syntax = "proto3";

package Contract;

option csharp_namespace = "GrpcCommonNet.Library.Contract";

import "google/protobuf/wrappers.proto";
import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";

import "protos/common/general.proto";
import "protos/common/contragent.proto";
import "protos/common/unit.proto";
import "protos/common/department.proto";
import "protos/common/currency.proto";
import "protos/common/product.proto";
import "protos/common/documenttype.proto";
import "protos/common/geolocation.proto";
import "protos/common/bankaccount.proto";



// Метаданные аудита
message Metadata {
  google.protobuf.Timestamp create_at = 1;      // Дата создания записи
  string create_by = 2;                         // Аббревиатура создателя записи
  int32 create_userid = 3;                      // Идентификатор создателя (пользователя)
  google.protobuf.Timestamp update_at = 4;      // Дата последнего редактирования записи
  string update_by = 5;                         // Аббревиатура последнего редактора записи
  int32 update_userid = 6;                      // Идентификатор последнего редактора (пользователя)
}

message Nomenclature {
	int32 goods_id = 1;
	string goods_short = 2;
	Common.Unit unit = 3;
}

enum ContractState {
	DRAFT  = 0;				// новый
	SENT_TO_CLIENT = 1;		// Передан заказчику
	SIGNED = 2;				// Подписан заказчиком
	ACTIVE = 3;				// Активен, есть операции
	COMPLITED = 4;			// Контракт исполнен
}

enum ProjectTypes {
	STANDART = 0;
	PROJECT =  1;
	SALE = 2;
}

message Manager {
  google.protobuf.Int32Value id = 1;								// Идентификатор менеджера
  optional string name = 2;							// ФИО менеджера
}

// Строка контракта
message Line {
  int32 id = 1;								// Идентификатор строки контракта
  int32 contract_id	= 2;					// Идентификатор контракта /допсоглашения / счета-договора
  google.protobuf.Int32Value previous_id	= 3;					// Идентификатор предыдущей строки контракта, которая была изменена
  Common.Unit unit = 4;                     // Единица измерения
  optional Common.Product product = 5;	            // Товара из справочника
  int32 order = 6;							// Порядковый номер строки
  string name = 7;							// Наименование в строке контракта
  Common.DecimalValue qty = 8;	            // Кол-во 
  Common.DecimalValue base_price = 9;
  Common.DecimalValue base_discount = 10;
  Common.DecimalValue discount_additional = 11;
  Common.DecimalValue price = 12;	        // Цена
  Common.DecimalValue amount = 13;	        // Сумма без НДС
  bool is_vat = 14;							// с НДС или без НДС
  Common.DecimalValue vat_prc = 15;			// Процент НДС
  Common.DecimalValue sum_vat = 16;	        // Сумма НДС
  Common.DecimalValue sum = 17;				// Сумма с НДС
  string comment = 18; 
  Common.DecimalValue round_for_line = 19;
  int32 specification = 20;
  string added_from = 21;
  Metadata metadata = 22;
  string operation = 23;
  Common.Contragent supplier = 24;

}

message TypeContract {
	int32 type_contract_id = 1;
	string type_contract_name = 2;
} 

// Представление контракта
message Contract {
  // Основные Идентификаторы
  int32 id = 1;											// Идентификатор контракта
  int32 direct = 2;										// Направление сделки относительно нашей компании: 0 - реализация (Seller = наша орг), 1 - приобретение.
  google.protobuf.Int32Value root_id = 3;									// Ссылка на Первичный контракт (основной) 
  google.protobuf.Int32Value previous_id = 4;								// Ссылка на Предыдущую запись, из которой "порождена" данная (цепочка допсоглашений)
  Common.DocumentType type_contract = 5;				// Тип контракта
  ContractState state = 6;										// Статус контракта (новый, выдан клиенту, заключен, в работе, завершен)

  // Контрагенты по контракту
  Common.Contragent seller = 7;							// Продавец (структура)
  Common.BankAccount bank_account_seller = 8;
  Common.Contragent buyer = 9;							// Покупатель (структура)
  Common.BankAccount bank_account_buyer = 10;
  Common.Contragent shipper = 11;						// Отправитель (структура)
  Common.Contragent consignee = 12;						// Получатель (структура)

  // Даты и номера
  google.protobuf.Timestamp date = 13;					// дата контракта (date -> Timestamp)
  google.protobuf.Timestamp expiration_date = 14;		// Дата окончания действия
  string number = 15;									// Номер контракта
  string name = 16;										// Наименование контракта. Например, "продажа лицензий на ПО"
  string doc_name = 17;									// Наименование документа. Например, "контракт" или "Договор"
  Common.Geolocation place_signed = 18;

  // Валюта и суммы (decimal храним как string для точности)
  Common.Currency currency = 19;                       // Валюта контракта (структура)
  Common.Currency currency_payment = 20;                        // Валюта контракта (структура)
  Common.DecimalValue sum = 21;                         // сумма с НДС (decimal -> string)
  Common.DecimalValue amount = 22;                      // сумма без НДС
  bool is_vat = 23;                                     // С НДС или без НДС
  Common.DecimalValue vat_prc = 24;                     // С НДС или без НДС
  Common.DecimalValue sum_vat = 25;                     // сумма НДС

  // Свободные данные JSON
  google.protobuf.Struct data = 26;

  // Дополнительные поля
  Common.Department department = 27;					// Идентификатор подразделение
  Manager initiator = 28;								// Инициатор 
  Manager executor = 29;								// Исполнитель
  ProjectTypes project_type =  30;

  int64 templdoc_id = 31;								// Идентификатор шаблона
  string comment = 32;									// Комментарий к контракту
  Metadata metadata = 33;								// Метаданные аудита
  
  repeated Line lines = 34;
}
  

// Класс для построения дерева контрактов
message NodeContract {
	int32 node_id = 1;
	int32 parent_node_id = 2;
	int32 tree_level = 3;								// 0,						       0,		  1,			  2
	string node_type = 4;								// contract_without_agreements, root, agreement, first_contract
	Contract contract = 5;
}

