syntax = "proto3";

option csharp_namespace = "GrpcCommonNet.Library.Common";

import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";
import "protos/common/general.proto";

package Common;

// Модель Проверено/Утверждено
message Checked {
	int32 id = 1;
	google.protobuf.Timestamp date = 2;
	string symbol = 3;
}

// Модель типа документа
message DocumentType {
	int32 id = 1;
	int32 parent = 2;
	string ids = 3;
	string parents = 4;
	string name = 5;
	string code = 6;
	int32 currency_type = 7;
	google.protobuf.Struct data = 8;
	int32 country_currency_id = 9;
	string view_master = 10;
	string view_detail = 11;
	bool is_default = 12;
	Checked approved = 13;
}