syntax = "proto3";

option csharp_namespace = "GrpcCommonNet.Library.Common";

import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";
import "protos/common/tree.proto";

package Common;

// Модель Проверено/Утверждено
message Checked {
	int32 id = 1;
	google.protobuf.Timestamp date = 2;
	string symbol = 3;
}

// Модель типа документа
message DocumentType {
	int32 id = 1;
	Tree parent = 2;
	string ids = 3;
	string parents = 4;
	string name = 5;
	string code = 6;
	string form = 7;
	int32 currency_type = 8;
	google.protobuf.Struct data = 9;
	int32 country_currency_id = 10;
	string view_master = 11;
	string view_detail = 12;
	bool is_default = 13;
	Checked approved = 14;
	int32 kind_id = 15;
}