syntax = "proto3";

option csharp_namespace = "GrpcCommonNet.Library.Common";

package Common;

//
// Основные сообщения
//

// Результат запроса. Должен быть в каждом response.
enum Status {
  Ok = 0;                                    // Запрос исполнен
  BadRequest = 1;                            // Ошибка в запросе
  Unauthorized = 2;                          // Неавторизован. Пользователь неизвестен, либо просточены все токены. 
  Forbidden = 3;                             // Пользоватедю отказано в доступе. Пользователь известен, но просрочен токен доступа.
  NotFound = 4;                              // Данные не найдены (не пустые, а их просто нет)
  InternalServerError = 5;                   // Внутренняя ошибка сервера
  ServiceUnavailable = 6;                    // Сервис недоступен
}

// Общий результат в ответе сервиса
message Result {
  Status status = 1;                           // Статус выполнения запроса
  optional string message = 2;                 // Сообщение сервера (например, описание ошибки)
}

//
// Кастомный Decimal
// Хранит число как целое значение + scale (10^-scale).
// Пример: units=12345, scale=2 => 123.45
//
message DecimalValue {
  int64 units = 1;  // целая часть + дробная без точки
  int32 scale = 2;  // степень для десятичной точки (кол-во знаков после запятой)
}

// Параметры постраничного вывода,например, { "page_number": 1, "page_size": 50 }
message Paging {				
  int32 page_number = 1;       // Номер страницы (начинается с 1)
  int32 page_size = 2;         // Размер страницы.  
  int32 total_count = 3;       // Кол-во   
}
