syntax = "proto3";

option csharp_namespace = "GrpcCommonNet.Library.Common";

package Common;

message Geolocation {
	int32  id = 1;						// Идентификатор географического местоположения
	optional int32  parent_id = 2;				// Родитель географического местоположения
	string name = 3;					// Наименование географического местоположения
	optional string ids  = 4;					// Список идентификаторы родительских географических местоположений и собственный идентификатор
	optional string names  = 5;					// Список наименований родительских географических местоположении и собственное наименование (путь)
	optional int32  is_country = 6;				// Признак страны
	optional string code2 = 7;					// Двухзначный код ТОЛЬКО ДЛЯ СТРАН
	optional string name_lat = 8;				// Наименование географического местоположения (латиница)
	optional string json_codes = 9;				// Json, содержащий коды географического местоположения. Заполнение для страны обязательно. 
													// Примеры: страна Узбекистан  { "Code2"; "UZ", "Code3"; "UZB", "CodeDigit"; 860}
													// город Ташкент {"SOATO": "1726"}
													// город Ахангаран {"SOATO": "1727212501"}
	optional string phone_code = 10;				// Телефонный код географического местоположения полны_. Например. у страны Узбекистан +998, у города Ташкента +998 71
	optional int32  lock = 11;					//  Флаг блокировки редактирования геолокаций
}

message Place {
	int32 id = 1;					// Идентификатор место расположения
	int32 parent_id  = 2;			// Родитель место расположения
	string name = 3;				// Наименование место расположения
	string ids = 4;					// Список идентификаторы родительских место расположения и собственный идентификатор
	string names = 5;				// Список наименований родительских место расположения и собственное наименование (путь)
	int32 geoLocation_id = 6;		// Идентификатор расположения места место расположения
	int32 lock = 7;					// Флаг блокировки редактирования места размещения
}